/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_S2S_V1_S2S_PB_H_INCLUDED
#define PB_S2S_V1_S2S_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef PB_BYTES_ARRAY_T(512) s2s_v1_AudioChunk_data_t;
/* A single chunk of raw audio bytes. */
typedef struct _s2s_v1_AudioChunk {
    /* Raw PCM (or the format negotiated during handshake) audio bytes. */
    s2s_v1_AudioChunk_data_t data;
} s2s_v1_AudioChunk;

/* Sentinel: no more audio will be sent. */
typedef struct _s2s_v1_FinishAudio {
    char dummy_field;
} s2s_v1_FinishAudio;

/* Top-level envelope for every client frame. */
typedef struct _s2s_v1_ClientMessage {
    pb_size_t which_payload;
    union {
        /* A raw audio chunk streamed from the microphone. */
        s2s_v1_AudioChunk audio_chunk;
        /* Signals that the client has finished sending audio for this session.
     After this the server drains any in-flight pipeline events and closes
     the connection gracefully. */
        s2s_v1_FinishAudio finish_audio;
    } payload;
} s2s_v1_ClientMessage;

/* ASR detected the onset of user speech (voice-activity detection).
 In interrupt mode the client should stop playback immediately. */
typedef struct _s2s_v1_ASRStartEvent {
    /* Unix epoch milliseconds when speech onset was detected. */
    int64_t timestamp_ms;
} s2s_v1_ASRStartEvent;

/* A transcription result — either an interim hypothesis or a final commit. */
typedef struct _s2s_v1_ASRResultEvent {
    int64_t timestamp_ms;
    char text[256];
    /* True if this is an unstable partial hypothesis; false if final and committed. */
    bool is_interim;
} s2s_v1_ASRResultEvent;

/* The ASR session has finished transcribing (no more results will follow). */
typedef struct _s2s_v1_ASRDoneEvent {
    int64_t timestamp_ms;
} s2s_v1_ASRDoneEvent;

/* A single streamed text chunk from the LLM response. */
typedef struct _s2s_v1_LLMDeltaEvent {
    int64_t timestamp_ms;
    char chunk[256];
    /* Zero-based position within the current response stream. */
    int32_t index;
} s2s_v1_LLMDeltaEvent;

/* The LLM has finished generating its response for this turn. */
typedef struct _s2s_v1_LLMDoneEvent {
    int64_t timestamp_ms;
    /* Approximate prompt + completion token counts (provider-specific). */
    int32_t prompt_tokens;
    int32_t completion_tokens;
} s2s_v1_LLMDoneEvent;

typedef PB_BYTES_ARRAY_T(512) s2s_v1_TTSDeltaEvent_chunk_t;
/* A single synthesised audio chunk from the TTS engine. */
typedef struct _s2s_v1_TTSDeltaEvent {
    int64_t timestamp_ms;
    /* Raw audio bytes (encoding matches the server's configured TTS format/rate). */
    s2s_v1_TTSDeltaEvent_chunk_t chunk;
    /* Zero-based position; chunks must be played in order. */
    int32_t index;
} s2s_v1_TTSDeltaEvent;

/* TTS synthesis for this turn is complete. */
typedef struct _s2s_v1_TTSDoneEvent {
    int64_t timestamp_ms;
    /* Number of characters submitted for synthesis. */
    int32_t chars_synthesised;
} s2s_v1_TTSDoneEvent;

/* A recoverable or fatal error from the server pipeline. */
typedef struct _s2s_v1_ErrorEvent {
    /* Machine-readable error code (e.g. "ASRUnavailableError"). */
    char code[64];
    /* Human-readable description. */
    char message[128];
    /* True if the session cannot continue after this error. */
    bool fatal;
} s2s_v1_ErrorEvent;

/* Top-level envelope for every server frame. */
typedef struct _s2s_v1_ServerMessage {
    pb_size_t which_payload;
    union {
        s2s_v1_ASRStartEvent asr_start;
        s2s_v1_ASRResultEvent asr_result;
        s2s_v1_ASRDoneEvent asr_done;
        s2s_v1_LLMDeltaEvent llm_delta;
        s2s_v1_LLMDoneEvent llm_done;
        s2s_v1_TTSDeltaEvent tts_delta;
        s2s_v1_TTSDoneEvent tts_done;
        s2s_v1_ErrorEvent error;
    } payload;
} s2s_v1_ServerMessage;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define s2s_v1_ClientMessage_init_default        {0, {s2s_v1_AudioChunk_init_default}}
#define s2s_v1_AudioChunk_init_default           {{0, {0}}}
#define s2s_v1_FinishAudio_init_default          {0}
#define s2s_v1_ServerMessage_init_default        {0, {s2s_v1_ASRStartEvent_init_default}}
#define s2s_v1_ASRStartEvent_init_default        {0}
#define s2s_v1_ASRResultEvent_init_default       {0, "", 0}
#define s2s_v1_ASRDoneEvent_init_default         {0}
#define s2s_v1_LLMDeltaEvent_init_default        {0, "", 0}
#define s2s_v1_LLMDoneEvent_init_default         {0, 0, 0}
#define s2s_v1_TTSDeltaEvent_init_default        {0, {0, {0}}, 0}
#define s2s_v1_TTSDoneEvent_init_default         {0, 0}
#define s2s_v1_ErrorEvent_init_default           {"", "", 0}
#define s2s_v1_ClientMessage_init_zero           {0, {s2s_v1_AudioChunk_init_zero}}
#define s2s_v1_AudioChunk_init_zero              {{0, {0}}}
#define s2s_v1_FinishAudio_init_zero             {0}
#define s2s_v1_ServerMessage_init_zero           {0, {s2s_v1_ASRStartEvent_init_zero}}
#define s2s_v1_ASRStartEvent_init_zero           {0}
#define s2s_v1_ASRResultEvent_init_zero          {0, "", 0}
#define s2s_v1_ASRDoneEvent_init_zero            {0}
#define s2s_v1_LLMDeltaEvent_init_zero           {0, "", 0}
#define s2s_v1_LLMDoneEvent_init_zero            {0, 0, 0}
#define s2s_v1_TTSDeltaEvent_init_zero           {0, {0, {0}}, 0}
#define s2s_v1_TTSDoneEvent_init_zero            {0, 0}
#define s2s_v1_ErrorEvent_init_zero              {"", "", 0}

/* Field tags (for use in manual encoding/decoding) */
#define s2s_v1_AudioChunk_data_tag               1
#define s2s_v1_ClientMessage_audio_chunk_tag     1
#define s2s_v1_ClientMessage_finish_audio_tag    2
#define s2s_v1_ASRStartEvent_timestamp_ms_tag    1
#define s2s_v1_ASRResultEvent_timestamp_ms_tag   1
#define s2s_v1_ASRResultEvent_text_tag           2
#define s2s_v1_ASRResultEvent_is_interim_tag     3
#define s2s_v1_ASRDoneEvent_timestamp_ms_tag     1
#define s2s_v1_LLMDeltaEvent_timestamp_ms_tag    1
#define s2s_v1_LLMDeltaEvent_chunk_tag           2
#define s2s_v1_LLMDeltaEvent_index_tag           3
#define s2s_v1_LLMDoneEvent_timestamp_ms_tag     1
#define s2s_v1_LLMDoneEvent_prompt_tokens_tag    2
#define s2s_v1_LLMDoneEvent_completion_tokens_tag 3
#define s2s_v1_TTSDeltaEvent_timestamp_ms_tag    1
#define s2s_v1_TTSDeltaEvent_chunk_tag           2
#define s2s_v1_TTSDeltaEvent_index_tag           3
#define s2s_v1_TTSDoneEvent_timestamp_ms_tag     1
#define s2s_v1_TTSDoneEvent_chars_synthesised_tag 2
#define s2s_v1_ErrorEvent_code_tag               1
#define s2s_v1_ErrorEvent_message_tag            2
#define s2s_v1_ErrorEvent_fatal_tag              3
#define s2s_v1_ServerMessage_asr_start_tag       1
#define s2s_v1_ServerMessage_asr_result_tag      2
#define s2s_v1_ServerMessage_asr_done_tag        3
#define s2s_v1_ServerMessage_llm_delta_tag       4
#define s2s_v1_ServerMessage_llm_done_tag        5
#define s2s_v1_ServerMessage_tts_delta_tag       6
#define s2s_v1_ServerMessage_tts_done_tag        7
#define s2s_v1_ServerMessage_error_tag           8

/* Struct field encoding specification for nanopb */
#define s2s_v1_ClientMessage_FIELDLIST(X, a) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,audio_chunk,payload.audio_chunk),   1) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,finish_audio,payload.finish_audio),   2)
#define s2s_v1_ClientMessage_CALLBACK NULL
#define s2s_v1_ClientMessage_DEFAULT NULL
#define s2s_v1_ClientMessage_payload_audio_chunk_MSGTYPE s2s_v1_AudioChunk
#define s2s_v1_ClientMessage_payload_finish_audio_MSGTYPE s2s_v1_FinishAudio

#define s2s_v1_AudioChunk_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, BYTES,    data,              1)
#define s2s_v1_AudioChunk_CALLBACK NULL
#define s2s_v1_AudioChunk_DEFAULT NULL

#define s2s_v1_FinishAudio_FIELDLIST(X, a) \

#define s2s_v1_FinishAudio_CALLBACK NULL
#define s2s_v1_FinishAudio_DEFAULT NULL

#define s2s_v1_ServerMessage_FIELDLIST(X, a) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,asr_start,payload.asr_start),   1) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,asr_result,payload.asr_result),   2) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,asr_done,payload.asr_done),   3) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,llm_delta,payload.llm_delta),   4) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,llm_done,payload.llm_done),   5) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,tts_delta,payload.tts_delta),   6) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,tts_done,payload.tts_done),   7) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,error,payload.error),   8)
#define s2s_v1_ServerMessage_CALLBACK NULL
#define s2s_v1_ServerMessage_DEFAULT NULL
#define s2s_v1_ServerMessage_payload_asr_start_MSGTYPE s2s_v1_ASRStartEvent
#define s2s_v1_ServerMessage_payload_asr_result_MSGTYPE s2s_v1_ASRResultEvent
#define s2s_v1_ServerMessage_payload_asr_done_MSGTYPE s2s_v1_ASRDoneEvent
#define s2s_v1_ServerMessage_payload_llm_delta_MSGTYPE s2s_v1_LLMDeltaEvent
#define s2s_v1_ServerMessage_payload_llm_done_MSGTYPE s2s_v1_LLMDoneEvent
#define s2s_v1_ServerMessage_payload_tts_delta_MSGTYPE s2s_v1_TTSDeltaEvent
#define s2s_v1_ServerMessage_payload_tts_done_MSGTYPE s2s_v1_TTSDoneEvent
#define s2s_v1_ServerMessage_payload_error_MSGTYPE s2s_v1_ErrorEvent

#define s2s_v1_ASRStartEvent_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, INT64,    timestamp_ms,      1)
#define s2s_v1_ASRStartEvent_CALLBACK NULL
#define s2s_v1_ASRStartEvent_DEFAULT NULL

#define s2s_v1_ASRResultEvent_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, INT64,    timestamp_ms,      1) \
X(a, STATIC,   SINGULAR, STRING,   text,              2) \
X(a, STATIC,   SINGULAR, BOOL,     is_interim,        3)
#define s2s_v1_ASRResultEvent_CALLBACK NULL
#define s2s_v1_ASRResultEvent_DEFAULT NULL

#define s2s_v1_ASRDoneEvent_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, INT64,    timestamp_ms,      1)
#define s2s_v1_ASRDoneEvent_CALLBACK NULL
#define s2s_v1_ASRDoneEvent_DEFAULT NULL

#define s2s_v1_LLMDeltaEvent_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, INT64,    timestamp_ms,      1) \
X(a, STATIC,   SINGULAR, STRING,   chunk,             2) \
X(a, STATIC,   SINGULAR, INT32,    index,             3)
#define s2s_v1_LLMDeltaEvent_CALLBACK NULL
#define s2s_v1_LLMDeltaEvent_DEFAULT NULL

#define s2s_v1_LLMDoneEvent_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, INT64,    timestamp_ms,      1) \
X(a, STATIC,   SINGULAR, INT32,    prompt_tokens,     2) \
X(a, STATIC,   SINGULAR, INT32,    completion_tokens,   3)
#define s2s_v1_LLMDoneEvent_CALLBACK NULL
#define s2s_v1_LLMDoneEvent_DEFAULT NULL

#define s2s_v1_TTSDeltaEvent_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, INT64,    timestamp_ms,      1) \
X(a, STATIC,   SINGULAR, BYTES,    chunk,             2) \
X(a, STATIC,   SINGULAR, INT32,    index,             3)
#define s2s_v1_TTSDeltaEvent_CALLBACK NULL
#define s2s_v1_TTSDeltaEvent_DEFAULT NULL

#define s2s_v1_TTSDoneEvent_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, INT64,    timestamp_ms,      1) \
X(a, STATIC,   SINGULAR, INT32,    chars_synthesised,   2)
#define s2s_v1_TTSDoneEvent_CALLBACK NULL
#define s2s_v1_TTSDoneEvent_DEFAULT NULL

#define s2s_v1_ErrorEvent_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   code,              1) \
X(a, STATIC,   SINGULAR, STRING,   message,           2) \
X(a, STATIC,   SINGULAR, BOOL,     fatal,             3)
#define s2s_v1_ErrorEvent_CALLBACK NULL
#define s2s_v1_ErrorEvent_DEFAULT NULL

extern const pb_msgdesc_t s2s_v1_ClientMessage_msg;
extern const pb_msgdesc_t s2s_v1_AudioChunk_msg;
extern const pb_msgdesc_t s2s_v1_FinishAudio_msg;
extern const pb_msgdesc_t s2s_v1_ServerMessage_msg;
extern const pb_msgdesc_t s2s_v1_ASRStartEvent_msg;
extern const pb_msgdesc_t s2s_v1_ASRResultEvent_msg;
extern const pb_msgdesc_t s2s_v1_ASRDoneEvent_msg;
extern const pb_msgdesc_t s2s_v1_LLMDeltaEvent_msg;
extern const pb_msgdesc_t s2s_v1_LLMDoneEvent_msg;
extern const pb_msgdesc_t s2s_v1_TTSDeltaEvent_msg;
extern const pb_msgdesc_t s2s_v1_TTSDoneEvent_msg;
extern const pb_msgdesc_t s2s_v1_ErrorEvent_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define s2s_v1_ClientMessage_fields &s2s_v1_ClientMessage_msg
#define s2s_v1_AudioChunk_fields &s2s_v1_AudioChunk_msg
#define s2s_v1_FinishAudio_fields &s2s_v1_FinishAudio_msg
#define s2s_v1_ServerMessage_fields &s2s_v1_ServerMessage_msg
#define s2s_v1_ASRStartEvent_fields &s2s_v1_ASRStartEvent_msg
#define s2s_v1_ASRResultEvent_fields &s2s_v1_ASRResultEvent_msg
#define s2s_v1_ASRDoneEvent_fields &s2s_v1_ASRDoneEvent_msg
#define s2s_v1_LLMDeltaEvent_fields &s2s_v1_LLMDeltaEvent_msg
#define s2s_v1_LLMDoneEvent_fields &s2s_v1_LLMDoneEvent_msg
#define s2s_v1_TTSDeltaEvent_fields &s2s_v1_TTSDeltaEvent_msg
#define s2s_v1_TTSDoneEvent_fields &s2s_v1_TTSDoneEvent_msg
#define s2s_v1_ErrorEvent_fields &s2s_v1_ErrorEvent_msg

/* Maximum encoded size of messages (where known) */
#define S2S_V1_S2S_PB_H_MAX_SIZE                 s2s_v1_ServerMessage_size
#define s2s_v1_ASRDoneEvent_size                 11
#define s2s_v1_ASRResultEvent_size               271
#define s2s_v1_ASRStartEvent_size                11
#define s2s_v1_AudioChunk_size                   515
#define s2s_v1_ClientMessage_size                518
#define s2s_v1_ErrorEvent_size                   197
#define s2s_v1_FinishAudio_size                  0
#define s2s_v1_LLMDeltaEvent_size                280
#define s2s_v1_LLMDoneEvent_size                 33
#define s2s_v1_ServerMessage_size                540
#define s2s_v1_TTSDeltaEvent_size                537
#define s2s_v1_TTSDoneEvent_size                 22

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
