/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9.1 */

#include "s2s.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#    error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(s2s_v1_ClientMessage, s2s_v1_ClientMessage, 2)

PB_BIND(s2s_v1_AudioChunk, s2s_v1_AudioChunk, 2)

PB_BIND(s2s_v1_FinishAudio, s2s_v1_FinishAudio, AUTO)

PB_BIND(s2s_v1_ServerMessage, s2s_v1_ServerMessage, 2)

PB_BIND(s2s_v1_ASRStartEvent, s2s_v1_ASRStartEvent, AUTO)

PB_BIND(s2s_v1_ASRResultEvent, s2s_v1_ASRResultEvent, 2)

PB_BIND(s2s_v1_ASRDoneEvent, s2s_v1_ASRDoneEvent, AUTO)

PB_BIND(s2s_v1_LLMDeltaEvent, s2s_v1_LLMDeltaEvent, 2)

PB_BIND(s2s_v1_LLMDoneEvent, s2s_v1_LLMDoneEvent, AUTO)

PB_BIND(s2s_v1_TTSDeltaEvent, s2s_v1_TTSDeltaEvent, 2)

PB_BIND(s2s_v1_TTSDoneEvent, s2s_v1_TTSDoneEvent, AUTO)

PB_BIND(s2s_v1_ErrorEvent, s2s_v1_ErrorEvent, AUTO)
