repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.14.1
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format
  - repo: https://github.com/tox-dev/pyproject-fmt
    rev: v2.5.0
    hooks:
      - id: pyproject-fmt
  - repo: https://github.com/google/yamlfmt
    rev: v0.20.0
    hooks:
      - id: yamlfmt
        exclude: '(^\.github/workflows/)'
  - repo: local
    hooks:
      - id: cmake-format
        name: cmake-format
        language: script
        entry: bash scripts/pre-commit/cmake-format.sh
        files: '(CMakeLists\.txt|\.cmake)$'
      - id: clang-format
        name: clang-format
        language: script
        entry: bash scripts/pre-commit/clang-format.sh
        files: '\.(c|h|cpp|cc|cxx|hpp|hh)$'
